### ISSUE TITLE
error when use autoplay

### ISSUE THREAD

**Issue by Alone-ankush** [brblacky/lavamusic#342]
### Bug description

when i put search platform **soundcloud** and using autoplay command.. i got this error.

![IMG_20221017_172335](https://user-images.githubusercontent.com/79055580/196170937-08cb1dff-166d-4f53-b0da-68c1e1794f26.jpg)

### Operating system

Linux

### Nodejs version

17.9.1

**Comment by NotAditya69** [comment]
firstly this is not any bug learn to fix your own cause mistakes and there's a support server for help rather than begging here for help for soundcloud you are supposed to use "scsearch" and only use the support server an if you don't know how to code either learn it or don't create unnecessary issues.

**Comment by nfsmaniac** [comment]
Ideally, a fetching of related songs at all supported sources should be implemented, not just the YouTube one.
#344 addresses an issue where no pre-check is done, if the music currently playing has YouTube origin.
